apiVersion: v1
kind: ReplicationController
metadata:
  name: final-replicas
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: final
        tier: frontend
    spec:
      containers:
      - name: final-app
        image: gcr.io/YOUR_PROJECT_ID/Final
        env:
        - name: PROCESSES
          value: final
        - name: PORT
          value: "8000"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: final-lb
  labels:
    app: final	
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: final
    tier: frontend
