apiVersion: v1
kind: ReplicationController
metadata:
  name: restaurant-finder-replicas
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: restaurant-finder
        tier: frontend
    spec:
      containers:
      - name: restaurant-finder-app
        image: gcr.io/YOUR_PROJECT_ID/restaurant-finder
        env:
        - name: PROCESSES
          value: restaurant-finder
        - name: PORT
          value: "8080"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-finder-lb
  labels:
    app: restaurant-finder	
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: restaurant-finder
    tier: frontend
